### ISSUE TITLE
Implement create service features

### ISSUE THREAD

**Issue by rafaelwillen** [rafaelwillen/kisalu-web#105]
## Tasks

- [x] Add the features images submission (includes deletion)
- [x] Place the description field as full width
- [x] Replace the price input with a masked one
- [x] Add the delivery time input
