### ISSUE TITLE
Create the services listing

### ISSUE THREAD

**Issue by rafaelwillen** [rafaelwillen/kisalu-web#107]
## Tasks

- [x] Implement the list item design (mobile and desktop)
- [x] Add actions for each item (delete, edit, set to draft, publish). It could be only be edited when is draft mode
- [x] Add search feature
- [x] Add the services for each tab
- [x] Persist the filtered state and search in the URL
